spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: li1234
    url: jdbc:mysql://localhost:3306/summer?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC

mybatis:
    map-underscore-to-camel-case: true
    mapper-locations: classpath:/mybatis/*.xml
    type-aliases-package: com.li.springboot_shiro.domain
